### ISSUE TITLE
Allow users to generate access keys for an URL

### ISSUE THREAD

**Issue by stgogm** [FinalDevStudio/pindale-dash#4]
Access keys considerations:
- Must be unique.
- Must be URL friendly (it will be used as a query param).
- Must be limited to a number of rooms.
- Must allow only one URL combination (*.example.com, stream.example.com, example.com, etc...)
- Associated URLs must use HTTPS protocol.

**Comment by stgogm** [comment]
The key must be limited to a number of rooms

**Comment by li0t** [comment]
The issue was closed on c1a7e7e3ace3ffbd680fecb0387a71cdae19dcb1.
